### ISSUE TITLE
lme.Rmd: final feedback

### ISSUE THREAD

**Issue by clayford** [uvastatlab/sme#13]
I like all your code and analysis! I think is a really helpful and complete example. Just three things I would like to see:

(1) I think some of the exposition is too concise. Pretend you are somebody who is new to mixed-effect models. What might confuse you? Some things that come to mind: 

- Why do we add `(1|block)` to the syntax? 
- What does the effect plot tell us? 
- What are the diagnostic plots? 
- What is ICC? What does "The likeness of egg production in the same block is .25." mean exactly? 
- Why is lmerTest loaded? What did it do? (The summary output looks the same.)
- The phrase "we can see in the summary that specifically, treatment O is significant less than treatment E." appears to contradict the confidence interval reported by emmeans.

(2) can you reference the performance package? The code `citation("performance")` should generate a BibTex entry that you can add to the refs.bib file. After the opening curly brace you'll need to enter a name, such as "performance", for example:

```
@Article{performance,
```
And then you can add the reference in the write-up using `[@performance]`.

(3) I'm not sure the plots needed jitter. The second one, in particular, at first glance looks like a scatter plot. I think these plots should just use `geom_point()`. 

Again, I love the code and analysis! I think it's spot on! I just want this to be more accessible to those who are not as experienced as you are with mixed-effect models.

**Comment by lkjamison** [comment]
Why do we add (1|block) to the syntax? - DONE
What does the effect plot tell us? - DONE
What are the diagnostic plots? - DONE
What is ICC? What does "The likeness of egg production in the same block is .25." mean exactly? - DONE
Why is lmerTest loaded? What did it do? (The summary output looks the same.) - DONE
The phrase "we can see in the summary that specifically, treatment O is significant less than treatment E." appears to contradict the confidence interval reported by emmeans. - Don't see this, I must have already changed it
(2) can you reference the performance package? The code citation("performance") should generate a BibTex entry that you can add to the refs.bib file. After the opening curly brace you'll need to enter a name, such as "performance", for example: - DONE

@Article{performance,
And then you can add the reference in the write-up using [@performance].

(3) I'm not sure the plots needed jitter. The second one, in particular, at first glance looks like a scatter plot. I think these plots should just use geom_point(). - DONE
