### ISSUE TITLE
lrm.Rmd: Logistic regression with numeric predictors (2) 

### ISSUE THREAD

**Issue by clayford** [uvastatlab/sme#16]
Write for someone who may be new to performing logistic regression in R. See the other examples for inspiration and ideas. When in doubt, talk it out.

1. Explore and get familiar with data. 
2. Fit a main effects model using all predictors. Shortcut syntax: `test ~ .`
3. Is it a good model?
4. Interpret the model.
5. Maybe visualize the model with effect plots.

**Comment by clayford** [comment]
Pulling this code out for now. This was for a question Faraway asked in his book. I think we should eventually include it, but thought it would be distracting having it in there while you're working on it. 

What is the difference in odds of testing positive for diabetes for a subject with BMI in the first quartile compared to a subject with BMI at the third quartile? [@faraway_book]

```
library(emmeans)
bmi_vals <- quantile(pima$bmi, probs = c(0.25,0.75))
rg <- ref_grid(m, at = list(bmi = bmi_vals))
emmeans(rg, specs = "bmi", type = "response") |>
  contrast("pairwise")
```

**Comment by lkjamison** [comment]
Explore and get familiar with data.- DONE
Fit a main effects model using all predictors. Shortcut syntax: test ~ .- DONE
Is it a good model?- DONE
Interpret the model.- DONE
Maybe visualize the model with effect plots.- DONE
