### ISSUE TITLE
lme.Rmd: Repeated-Measures model 

### ISSUE THREAD

**Issue by clayford** [uvastatlab/sme#17]
Write for someone who may be new to repeated measures analysis in R. See the other examples for inspiration and ideas. When in doubt, talk it out.

1. Explore and get familiar with data. 
2. Model activate as a function of treatment and brain region. Do we need an interaction?
3. Is it a good model?
4. Interpret the model and perform follow-up comparisons.
5. Maybe visualize the model with effect plots.

**Comment by lkjamison** [comment]
Explore and get familiar with data. - Done
Model activate as a function of treatment and brain region. Do we need an interaction?- Done
Is it a good model?- Done
Interpret the model and perform follow-up comparisons.- Done
Maybe visualize the model with effect plots.- Done
