### ISSUE TITLE
lm.Rmd: Linear model with categorical and numeric predictors

### ISSUE THREAD

**Issue by clayford** [uvastatlab/sme#4]
Visualize the following and add appropriate commentary:
- distribution of bp
- distribution of bp by sex
- scatterplot of bp (y-axis) versus obese (x-axis)

Example: plot(bp ~ obese, data = bp.obese)

About the data: The bp.obese data frame has 102 rows and 3 columns. It contains data from a random sample of Mexican-American adults in a small California town.

**Comment by clayford** [comment]
Hi Oyin.

Love the plots. Great work. 

You may want to consider adding a little more exposition. For example, "First, we will look at summary statistics of the data. We see sex is a 0/1 variable where 0 is male and 1 is female. The mean of 0.5686 tells us about 57% of the data are females. The obese variable is a ratio of actual weight to "ideal" weight. Since most of the data is over 1, it appears the majority of subjects are heavier than their ideal weight."

Same with the plots. Something like "Blood pressure looks slightly skewed right with no major differences between sexes." 

When comparing two distributions, using `geom_density()` may be easier to read. Currently the histogram bars are "stacked" counts. If you replace `geom_histogram()` with `geom_density(alpha = 1/3)` you get two smooth histograms layered on each other. That allows us to compare the relative distribution of blood pressure between sexes without having to mentally account for the stacked counts.

Again, I think it would be good to comment on the scatter plot as well. The relationship is positive, but obesity does not completely explain blood pressure. I think it's interesting the most "obese" subjects have fairly normal blood pressure, while those with highest blood pressure values belong to those in the "normal" range of obesity. In other words, the upper right quadrant is empty. 

I think these kinds of observations will be helpful to readers (and future StatLab associates) about why we summarize and visualize data.

Clay

**Comment by oadenekan123** [comment]
I did not even realize that the counts were stacked! I should have been more careful with that. Thank you for pointing it out.
