### ISSUE TITLE
lrm.Rmd: Logistic regression with numeric predictors (1)

### ISSUE THREAD

**Issue by clayford** [uvastatlab/sme#5]
Visualize the following and add appropriate commentary:
- distribution of ab by mal
- distribution of log(ab) by mal
- distribution of age by mal

Example: boxplot(log(ab) ~ mal, data = malaria)

About the data: A random sample of 100 children aged 3–15 years from a village in Ghana. The children were followed for a period of 8 months. At the beginning of the study, values of a particular antibody were assessed. Based on observations during the study period, the children were categorized into two groups: individuals with (1) and without symptoms of malaria (0).

**Comment by slomuscio** [comment]
What is the best way to split the data into testing and training data sets?

**Comment by slomuscio** [comment]
How do we make the model reproducible?

**Comment by slomuscio** [comment]
Stuck on confusion matrix, keeps giving this error: 

Error: `data` and `reference` should be factors with the same levels.

**Comment by clayford** [comment]
I'm not sure I would split the data into test and train since there are only 100 records. But if you feel strongly about it, you could do something like the following:

```
set.seed(1)  # make reproducible
i <- sample(x = nrow(malaria), size = floor(0.75*nrow(malaria)))
malaria.train <- malaria[i,]
malaria.test <- malaria[-i,]
```

**Comment by slomuscio** [comment]
Okay, cool thanks! Is there a cut off around which we should start splitting the data into testing and training sets? Like if we have more than X records we split the data into testing and training sets?

**Comment by clayford** [comment]
I'm not aware of a general cut off. The whole test/train thing is about validating the model. How will the model perform on new "wild" data that was not used to build the model? If you're not going to use the model for making predictions, then arbitrarily splitting the data is wasteful. If you are going to make predictions, and data is limited, then I would do bootstrap model validation instead so all of the data is used to build the model. If you have lots and lots of data, and the ratio of data to predictors is huge, then I guess splitting the data would be ok to do. But I think cross validation would be better to validate the model than just doing a single test/train split. I realize there are many researchers who advocate for test/train every time you run an analysis. Sorry if I'm confusing you.

**Comment by clayford** [comment]
Hi Sam.

It looks like you've tackled the analysis. That's great. But don't forget to create a few plots. I made a few suggestions above. I think exploratory plots are a good way to get to know the data and I think it sets a good example for readers (and future StatLab associates). I think adding some exposition would be good as well. Maybe after calling `summary()` on the data frame noting things like "We see mal is coded as 0/1 (where 1 indicates risk of malaria), with 27% of the data being 1. The distribution of ab is quite skewed, with a mean 3 times larger than the median." That sort of thing.

Same with the plots once you create them. What do we notice about the distribution of age and ab between those at risk of malaria and those not at risk.

It may help to set mal as a factor, like so: `malaria$mal <- factor(malaria$mal)`

Clay

**Comment by clayford** [comment]
Fantastic work!
