### ISSUE TITLE
lme.Rmd: multilevel modeling

### ISSUE THREAD

**Issue by clayford** [uvastatlab/sme#6]
Visualize the following and add appropriate commentary:
- distribution of egs by treat
- distribution of eggs by block

Example: stripchart(eggs ~ block, data = eggprod)

About the data: The eggprod data frame has 12 rows and 3 columns. Six pullets were placed into each of 12 pens. Four blocks were formed from groups of 3 pens based on location. Three treatments were applied. The number of eggs produced was recorded.

**Comment by lkjamison** [comment]
The below code will read in the data, create lists of eggs by treat and block then produce corresponding stripcharts.

`# Install Packages and Load Data ------------------------------------------
library(faraway)
data(eggprod)
str(eggprod)


# Create Stripcharts ------------------------------------------------------
treat <- list("E"=eggprod[eggprod$treat=="E","eggs"], 
              "F"=eggprod[eggprod$treat=="F","eggs"],
              "O"=eggprod[eggprod$treat=="O","eggs"])

stripchart(treat,
           main="Eggs by Treat",
           xlab="Eggs",
           ylab="Treat",
           method="jitter",
           col=c("orange","red","blue"),
           pch=16
)

block <- list("1"=eggprod[eggprod$block=="1","eggs"], 
              "2"=eggprod[eggprod$block=="2","eggs"],
              "3"=eggprod[eggprod$block=="3","eggs"],
              "4"=eggprod[eggprod$block=="4","eggs"])

stripchart(block,
           main="Eggs by Block",
           xlab="Eggs",
           ylab="Block",
           method="jitter",
           col=c("orange","red","blue","green"),
           pch=16
)`

**Comment by clayford** [comment]
Hi Laura.

Great work. I like the plots. I really like the comments!

I might reconsider using `geom_violin()` since there are only a few data points. The density curve is being estimated based on 3 or 4 points, which seems small to me. For example, the distribution for treatment E is estimated to be bimodal, but the second hump is based on 1 point. The distribution could be unimodal and skewed. It's hard to say. 

Jittering doesn't seem necessary either, but I suppose it doesn't hurt. It seems like it would be easier on the eyes if they were all in a single line since were only dealing with 12 points. I've always approached jittering as something we do when we have overplotting. I don't think that's an issue here. 

Clay
